/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package novisualbd;

import java.util.Random;

/**
 *
 * @author ederd
 */
public class VisualPassword extends javax.swing.JPanel {
    private int minimo;
    private int maximo;
    private boolean mayusculas;
    private boolean minuscula;
    private boolean numero;
    private boolean caracterEspecial;
    private boolean visibleEtiqueta;

    public VisualPassword(int minimo, int maximo, boolean mayusculas, boolean minuscula, boolean numero, boolean caracterEspecial,boolean visibleEtiqueta) {
        this.minimo = minimo;
        this.maximo = maximo;
        this.mayusculas = mayusculas;
        this.minuscula = minuscula;
        this.numero = numero;
        this.caracterEspecial = caracterEspecial;
        this.visibleEtiqueta=visibleEtiqueta;
        
    }

    public boolean getVisibleEtiqueta() {
        return visibleEtiqueta;
    }

    public void setVisibleEtiqueta(boolean visibleEtiqueta) {
        this.visibleEtiqueta = visibleEtiqueta;
        lblGeneradorPassword.setVisible(visibleEtiqueta);
    }

    public int getMinimo() {
        return minimo;
    }

    public void setMinimo(int minimo) {
        this.minimo = minimo;
    }

    public int getMaximo() {
        return maximo;
    }

    public void setMaximo(int maximo) {
        this.maximo = maximo;
    }

    public boolean isMayusculas() {
        return mayusculas;
    }

    public void setMayusculas(boolean mayusculas) {
        this.mayusculas = mayusculas;
    }

    public boolean isMinuscula() {
        return minuscula;
    }

    public void setMinuscula(boolean minuscula) {
        this.minuscula = minuscula;
    }

    public boolean isNumero() {
        return numero;
    }

    public void setNumero(boolean numero) {
        this.numero = numero;
    }

    public boolean isCaracterEspecial() {
        return caracterEspecial;
    }

    public void setCaracterEspecial(boolean caracterEspecial) {
        this.caracterEspecial = caracterEspecial;
    }
     public String generatePassword() {
        StringBuilder password = new StringBuilder();
        Random random = new Random();

        int passwordLength = random.nextInt(maximo - minimo + 1) + minimo;

        String allChars = "";
        if (mayusculas) {
            allChars += "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        }
        if (minuscula) {
            allChars += "abcdefghijklmnopqrstuvwxyz";
        }
        if (numero) {
            allChars += "0123456789";
        }
        if (caracterEspecial) {
            allChars += "@$!%#*?&";
        }

        for (int i = 0; i < passwordLength; i++) {
            password.append(allChars.charAt(random.nextInt(allChars.length())));
        }

        return password.toString();
    }
    public String getPassword(){
        return passwordField.getPassword().toString();
    }
    

    /**
     * Creates new form VisualPassword
     */
    public VisualPassword() {
        initComponents();
        lblGeneradorPassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField = new javax.swing.JPasswordField();
        toglebtnOjo = new javax.swing.JToggleButton();
        lblGeneradorPassword = new javax.swing.JLabel();

        passwordField.setText("jPasswordField1");

        toglebtnOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novisualbd/ojo2.png"))); // NOI18N
        toglebtnOjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toglebtnOjoActionPerformed(evt);
            }
        });

        lblGeneradorPassword.setText("Generarar contraseña");
        lblGeneradorPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGeneradorPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneradorPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toglebtnOjo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toglebtnOjo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGeneradorPassword)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toglebtnOjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toglebtnOjoActionPerformed
        // TODO add your handling code here:
        if(toglebtnOjo.isSelected()){
            passwordField.setEchoChar((char)0);
        }else{
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_toglebtnOjoActionPerformed

    private void lblGeneradorPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeneradorPasswordMouseClicked
        // TODO add your handling code here:
        passwordField.setText(generatePassword());
    }//GEN-LAST:event_lblGeneradorPasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblGeneradorPassword;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JToggleButton toglebtnOjo;
    // End of variables declaration//GEN-END:variables
}
